<a href="https://colab.research.google.com/github/ShauryaPrakashVerma/Python_for_AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np

# 1D array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# changing the dtype of the array
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [4]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 # with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
print(np.ones((3,4)))
print(np.zeros((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# np.random   --> creates array of size 3 x 4 od random numbers.
np.random.random((3,4))

array([[0.44671012, 0.07177169, 0.04821212, 0.52082844],
       [0.84174929, 0.67466496, 0.56277777, 0.8363905 ],
       [0.03681335, 0.24175533, 0.71916873, 0.79236646]])

In [ ]:
# np.linspace --> linearly spaced array
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity --> creates an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim --> no of dimensions of the array
a3.ndim

3

In [ ]:
# shape
print(a2.shape)
a3

(3, 4)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# no of items
a3.size

8

In [ ]:
# itemsize ---> what size does item occupy in memory
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
# relational operators
a2 > 5
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[60., 28.,  7.],
       [71., 83., 71.],
       [21., 30., 42.]])

In [ ]:
# max/min/sum/prod
# 0 -> columnwise and 1 -> rowwise
print(np.max(a1,axis = 0))
np.prod(a1,axis=0)

[71. 83. 71.]


array([89460., 69720., 20874.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([474.88888889,  32.        ,  74.        ])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.30481062,  0.27090579,  0.6569866 ],
       [ 0.95105465,  0.96836446,  0.95105465],
       [ 0.83665564, -0.98803162, -0.91652155]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
print(np.log(a1))
print("==============")
print(np.exp(a1))

[[4.09434456 3.33220451 1.94591015]
 [4.26267988 4.41884061 4.26267988]
 [3.04452244 3.40119738 3.73766962]]
[[1.14200739e+26 1.44625706e+12 1.09663316e+03]
 [6.83767123e+30 1.11286375e+36 6.83767123e+30]
 [1.31881573e+09 1.06864746e+13 1.73927494e+18]]


In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[86., 16., 28.],
       [15.,  2., 71.]])

### Indexing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a1[-1])

9


In [ ]:
print(a2[1][2])
print(a2[1,2])

6
6


In [ ]:
print(a3[1][0][1])
print(a3[1,0,1])

5
5


# Slicing

In [ ]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a1[2:5:2])
print(a1[2:5])

[2 4]
[2 3 4]


In [ ]:
print(a2)
print('-------------')
print(a2[::2,1::2])
print('-------------')
print(a2[1,::3])
print('-------------')
print(a2[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[[ 1  3]
 [ 9 11]]
-------------
[4 7]


In [ ]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

print('-------------')
print(a3[::2,0,::2])

print('-------------')
print(a3[::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------
[[ 0  2]
 [18 20]]


### Iterating

In [ ]:
a1
# 1D
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# 2D
for i in a2:
  print(i)  # each i is a 1D array (row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)   # each i is a 2D array ()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# to loop through each item
# first converts into 1D and then prints each one of them (works on any dimension)
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
print(np.transpose(a2))

# both are different syntax for transposing
print(a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# ravel  ---> converts any dimension array into 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### result diikh jaae to temporary operation, if result not visible then the changes are permanent in the original source

### Stacking
- Pre-requisite is that the shape should be same.

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))  # horizontal stacking (combined)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking  (combined on top and bottom)
np.vstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# splitting has to be done in equal parts

In [ ]:
# vertical split
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
np.vsplit(a4,2)

ValueError: array split does not result in an equal division

# Numpy array vs Pyhton lists

In [6]:
# speed
# lists

a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c = []
import time
start = time.time()

for i in range(len(a)):
  c.append(a[i] + b[i])

print(time.time() - start)

2.36834716796875


In [7]:
# in munpy array performing the same task

# numpy performs the same task in a faster way
# since it is based on c array and it is not referential array
# instead of the addresses the actual values are stored

import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start = time.time()
c = a+b
print(time.time()-start)

0.3730454444885254


In [8]:
# memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [12]:
a =  np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

### Hence numpy is better than pyhton lists since it has better speed, occupies less memory, and is much more convenient to use.

# Advanced Indexing

In [16]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
# Fancy indexing
a[[0,2,3]]    # list is provided with the indices of the rows i want to fetch

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [19]:
a[:,[[0,2,3]]]    # column 0,2 and 3

array([[[ 0,  2,  3]],

       [[ 4,  6,  7]],

       [[ 8, 10, 11]],

       [[12, 14, 15]],

       [[16, 18, 19]],

       [[20, 22, 23]]])

In [22]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)

In [25]:
# find all the numbers greater than 50
a > 50
# ---> result is a boolean array
# ---> we can perform boolean masking
a[a>50]

# boolean masking overlapping boolean array with the array a , and only the true values remain
# good way of filtering data ased on certain condition

array([78, 95, 54, 66, 65, 83, 96, 80, 99])

In [27]:
# find out even numbers
a[a % 2 ==0]

array([78, 54, 46, 18, 24, 66, 42, 96, 50, 20,  4, 30, 80, 42])

In [32]:
# find all the numbers greater than 50 and also even
print((a%2 == 0) & (a> 50))
# using '&' because we are wroking with boolean values,
# so we use bitwise operator
# & is a bitwise operator

print(a[(a%2 == 0) & (a> 50)])

[[ True False  True False]
 [False False  True False]
 [False False False  True]
 [False False False False]
 [False False False  True]
 [False False False False]]
[78 54 66 96 80]


# Broadcasting
- term broadcasting describes how numpy treats different hapes during differetn operations

- the smaller array is broadcasr across the larger array so that they have compatible shapes.

In [37]:
a= np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)


print('------------------')
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
------------------
[[0 2 4]
 [3 5 7]]
